export const assets = [
  { name: "bullet", url: "./bullet.png" },
  { name: "enemy", url: "./enemy.png" },
  { name: "player", url: "./player.png" },
  { name: "bg", url: "./bg.png" },
  { name: "laser", url: "./laser.mp3" },
  { name: "explosion", url: "./explosion.mp3" },
  { name: "win", url: "./win.mp3" },
  { name: "lose", url: "./lose.mp3" },
  { name: "boom01", url: "./boom01.png" },
  { name: "boom02", url: "./boom02.png" },
  { name: "boom03", url: "./boom03.png" },
  { name: "boom04", url: "./boom04.png" },
  { name: "boom05", url: "./boom05.png" },
  { name: "boom06", url: "./boom06.png" },
  { name: "boom07", url: "./boom07.png" },
  { name: "boom08", url: "./boom08.png" },
  { name: "boom09", url: "./boom09.png" },
  { name: "boom10", url: "./boom10.png" },
  { name: "boom11", url: "./boom11.png" },
];

export const explosionFrames = [
  "boom01",
  "boom02",
  "boom03",
  "boom04",
  "boom05",
  "boom06",
  "boom07",
  "boom08",
  "boom09",
  "boom10",
  "boom11",
];
